# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeviceManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeviceManager
    pod 'SwiftLint'
    
end
